name: output_test
on:
  workflow_dispatch:

jobs:
  change_pass:
    runs-on: ubuntu-latest
    outputs:
      oldpass_vfdprm1: ${{ steps.set-pass.outputs.oldPass_vfdprm1 }}
      newpass_vfdprm1: ${{ steps.set-pass.outputs.newPass_vfdprm1 }}
    steps:
      - id: set-pass
        run: |
          NEWPASS=vfdprm1.$(date +"%b@%Y")
          OLDPASS=vfdprm1.$(date -d "1 month ago" +"%b@%Y")
          echo "oldPass_vfdprm1=$OLDPASS" >> "$GITHUB_OUTPUT"
          echo "newPass_vfdprm1=$NEWPASS" >> "$GITHUB_OUTPUT"
          
  job2:
    runs-on: ubuntu-latest
    needs: change_pass
    steps:
      - name: check the output values
        if: contains(needs.change_pass.outputs.oldpass_vfdprm1,'vfdprm1')
        env:
          OLDPASS: ${{ needs.change_pass.outputs.oldpass_vfdprm1 }}
          NEWPASS: ${{ needs.change_pass.outputs.newpass_vfdprm1 }}
        run: |
          echo -e "oldpass=$OLDPASS\n\nnewpass=$NEWPASS"
    
